services:
  - docker
notifications:
  email: false
git:
  quiet: true
  depth: false
language: node_js
node_js: lts/*
python: 3.7
matrix:
  include:
    - python: 3.7
services:
  - xvfb
  - docker
addons:
  apt:
    update: false
    packages:
      - jq
      - bash
      - curl
      - tree
      - docker-ce
      - libxml2-utils
      - libappindicator1
      - fonts-liberation
      - google-chrome-stable
      - python3-setuptools
      - python3-pip
install: true
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  #
  - |
    if [ ! -f ${HOME}/.local/daggerok/bash-functions/master/main.bash ] ; then
      mkdir -p ${HOME}/.local/daggerok/bash-functions/master ;
      curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
    fi
    source ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
  - stop_any 80 5432 8080 8081 8082 8083 8084 8085 8086 8087 8088
  #
  - export PATH=$HOME/.local/bin:$PATH
  - pip -V
  - docker-compose version
  - pip3 install --user --upgrade pip
  - pip install --user --upgrade httpie docker-compose
  - http --version --debug
  - pip -V
  #
  - stop_any 8080 5432 3000 80
  - docker-compose version
script:
  - export root=$(pwd)
  #
  - cd ${root}/cypress-testing
  #- export CI=1
  - npm i
  - npm run cypress-install
    # see: https://docs.cypress.io/guides/guides/continuous-integration.html#Advanced-setup
  - sudo apt-get update -yqq >/dev/null
  - sudo apt-get install -y xvfb libgtk-3-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
  - npm run cypress-run
  #
  - docker pull cypress/included:3.2.0
  - docker run -it -v $(pwd):/e2e -w /e2e -e CI=1 --entrypoint cypress cypress/included:3.2.0 run
  #
  - docker pull cypress/browsers:node8.9.3-chrome73
  - docker run -it -v $(pwd):/e2e -w /e2e -e CI=1 cypress/browsers:node8.9.3-chrome73 bash -c 'npm i ; npm i cypress ; $(npm bin)/cypress run --browser chrome'
  #
  - docker pull cypress/browsers:node8.9.3-chrome73
  - docker run -it -v $(pwd):/e2e -w /e2e -e CI=1 cypress/browsers:node8.9.3-chrome73 bash -c 'npm i ; npm run cypress-install ; npm run cypress-run -- --browser chrome'
  #
  - cd ${root}/composing-software
  - npm i
  - npm t
  #
  - cd ${root}/karma-parcel-starter
  - npm i
  - npm t
  #
  - cd ${root}/first-blood
  - npm i
  - npm run predeploy
cache:
  directories:
    - composing-software/node_modules
    - karma-parcel-starter/node_modules
    - first-blood/node_modules
    - ~/.local/daggerok
    - ~/.docker
    - ~/.n*
  packages: true
  npm: true
before_deploy:
  - cd ${root}/first-blood
  - npm run predeploy
env:
  global:
    - TERM=dumb
    # travis encrypt GITHUB_TOKEN=<your github repo token> --add
    - secure: WoldedqeTGkuSxO/9KyM5vU7BRAb6ALrq0bjY225aSOtJ32p1VhOrCnqK9eyGF+g/nyOP++zvq6k1dLXwCRddc3TkK9IUb9DN56h3pcDl8EYuihc33h6URXooqNC12VtBEn0qF07UYa3cIWaRM4XRMxWt/CsivNp1DH+crf1UeCAx7+RQeubwXpopeD/qfb3Saa+fEaK4ZLfpMULPctfeoFxckSE03fQgD3H5zZiQ53l7niInjc8Czxaky3EM+E/q6MQiBuKEh3q98tOgEtggKa6eV721bnnIfA3aggc7ha4DUJDToRFcQuyA+6t9jWWZFpQUZn3Q4k0VRmr0coSGXPFxHZCsqKfnO0bW1GOhX0AmxI3K8lXjLq7e6/FhRjWGdJmHBCJsViQ+CYH8aw9GRy2Ydn8+EQ6anigphtx58B15NGFVyyFiQA8Fu+87sBaXBzJeTHZen8Z3mNFJsFgMRSLL15jDrB53IWjvuwr2beFWjZEngIbDaMZTB8yY2xeZ+pnVLDtbMKFIg8M/7xWr0ZoQZFqQft4VPhzr5A/n5ThX4+2YJ1ASbJS1XxnlIqjbswDKKYXwgajAw9lHqtL+FcmWZ8N5fiRTfoH6T95flD0R6+XH7ei2ZF3G6S9co+fuAj8SYLrLK+9Cin79NhG2PoHvZ5jDz2Pkpy3VIFCXMg=
deploy:
  provider: pages
  skip-cleanup: true
  # travis encrypt GITHUB_TOKEN=<your github repo token> --add
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: first-blood/dist
