notifications:
  email: false
git:
  quiet: true
  depth: 1
env:
  global:
    TERM=dumb
language: node_js
node_js: lts/*
apt_packages:
  - curl
install: true
script:
  - export root=$(pwd)
  - cd ${root}/first-blood
  - npm i
  - npm run predeploy
cache:
  directories:
    - node_modules/
    - $HOME/.npm
  packages: true
  npm: true
  yarn: true
